version: 0.2
phases:
  install:
    commands:
      - yarn install
  pre-build:
    commands:
      - npm test -- --coverage --watchAll=false
  build:
    commands:
      - yarn build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
