version: 0.2
phases:
  install:
    commands:
      - yarn install
      - echo google-chrome --version 
  pre_build:
    commands:
      - npm test -- --coverage --watchAll=false
      - npx nightwatch -e chrome --headless
  build:
    commands:
      - yarn build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
